### ISSUE TITLE
kmer_model.pkl is empty

### ISSUE THREAD

**Issue by Naturalist1986** [AuslanderLab/kmermaid#4]
Hi, is kMermaid currently active? When I try to download the model I get a txt file.

**Comment by Naturalist1986** [comment]
Hi, Anastasia

Yes I tried this way first but it only download a small text file with this inside:

version https://git-lfs.github.com/spec/v1
oid sha256:070eb87efb3313f4a470fd78a89702ce78c6e18d45655bdb77c1e1c439fec603
size 281503837

**Comment by anastasia-lucas** [comment]
Hi @Naturalist1986, thanks for clarifying. I see you are correct. It seems like the file doesn't exist on the LFS server anymore. 

I will work to resolve this. In the meantime, you can download the file from here and copy it into the correct directory 

https://upenn.box.com/s/za5v570au1kponog0tavlgrtob7t6zbw
